### ISSUE TITLE
lots of callback URLs break the table line [CLI-36]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#105]
Do we have a way to print callback URLs in a way that doesn't break lines? eg replacing `,` with CRLF of some sort?

![image](https://user-images.githubusercontent.com/175880/108734036-cd0ae500-750d-11eb-83b8-a69b274e7eac.png)

**Comment by Widcket** [comment]
The URLs have been removed from the table view on `v0.2.0`.
