### ISSUE TITLE
Apis show should show scopes [CLI-71]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#150]
for `apis show` instead of the amount of scopes, show the actual scopes

![image](https://user-images.githubusercontent.com/175880/111000145-4739c700-8360-11eb-9b8d-ab7e7bc7d0a8.png)

**Comment by Widcket** [comment]
The thing with the scopes is that they will usually overflow the line length, so we'll have to truncate them. There's a command to list all the scopes an API has for this reason.

I'll add a card to track this (showing the truncated list of scopes). Thanks!

**Comment by woloski** [comment]
You mean on the list command? I am talking about the `show` command.

**Comment by Widcket** [comment]
This is the existing `auth0 apis scopes list <client-id>` command.
<img width="363" alt="Screen Shot 2021-03-12 at 18 36 37" src="https://user-images.githubusercontent.com/5055789/111001114-f4f9a580-8361-11eb-96bd-cf61894f0d2f.png">

**Comment by Widcket** [comment]
> You mean on the list command? I am talking about the `show` command.

So you suggest we show the whole list of scopes on the `show` command, and indent/format accordingly in multiple lines?

**Comment by woloski** [comment]
ahh I see now. ok, maybe we can hint the user to run `auth0 apis scopes list {id}` to see all the scope details
> To see the full scope list, run `auth0 apis scopes list {id}`

**Comment by Widcket** [comment]
Added the card [CLI-71](https://auth0team.atlassian.net/browse/CLI-71) to track this.
