### ISSUE TITLE
Hint after test login [CLI-72]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#152]
after running test login (for the first time) we can hint the dev at running quickstart download

> Login flow is working! Next, try download and run a quickstart `auth0 quickstarts download {client_id}`

**Comment by Widcket** [comment]
Added the card [CLI-72](https://auth0team.atlassian.net/browse/CLI-72) to track this.

**Comment by cyx** [comment]
This has actually been done. 

See: https://github.com/auth0/auth0-cli/blob/main/internal/cli/test.go#L128
