### ISSUE TITLE
Hint after download qs [CLI-74]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#153]
After download qs let's hint with:

> Quickstart sample sucessfully downloaded at ...
> cd test-app/sample-01 and read README.md

**Comment by Widcket** [comment]
Added the card [CLI-74](https://auth0team.atlassian.net/browse/CLI-74) to track this.

**Comment by Widcket** [comment]
Superseded by https://github.com/auth0/auth0-cli/issues/191. Also removed the card.
