### ISSUE TITLE
actions create should create an action file by default

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#157]
The default experience on `auth0 actions create` should be to create a "noop" action, write it to the file system and upload it.
Specifying an action file should be a special case (`--file myaction.js`)

After creating and upload the action we should tell the user
> Edit the action code by opening `action-name.js` and deploy it using `auth0 actions deploy {new-action-id}`

**Comment by Widcket** [comment]
Closing since we'll be removing the `actions` commands in favor of `rules` commands for the time being.
