### ISSUE TITLE
no idea what to do on actions flows update

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#158]
![image](https://user-images.githubusercontent.com/175880/111007186-05fbe400-836d-11eb-8757-01a8c88c86af.png)

What is a file containing the bindings? I suggest, if there is no bindings, offer generating one with a default content.

> There are no action bindings for `trigger`. Do you want to generate one?
> post-login-bindings.js generated

**Comment by Widcket** [comment]
Closing since we'll be removing the `actions` commands in favor of `rules` commands for the time being.
