### ISSUE TITLE
Default experience of `test login` should be to show the JSON output [CLI-73]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#159]
The default experience of test login should be to show the JSON output. This should include these properties: user_info, id_token_decoded, access_token_decoded, id_token, access_token

This is useful for troubleshooting which is the main goal of the CLI. As an example of this, I added an action that add an attribute to the id_token and when I did test login it didn't show up in the response
![image](https://user-images.githubusercontent.com/175880/111007649-1d879c80-836e-11eb-913b-28e4a25049a4.png)

**Comment by Widcket** [comment]
Added the card [CLI-73](https://auth0team.atlassian.net/browse/CLI-73) to track this. Included in it that the JSON should be syntax-highlighted for better readability.
