### ISSUE TITLE
Support specifying an audience in test login [CLI-84]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#184]
in the same way we allow specifying client and connection, we should allow specifying audience

**Comment by cyx** [comment]
Just to clarify, internally this means:

1. If it looks like an audience, first fetch the API via the audience.
2. After fetching the API, we fetch the client from that. (This part is fuzzy).

**Comment by woloski** [comment]
no. Audience is just a param of authorize. Pass as-is

**Comment by Widcket** [comment]
Tracking this on [CLI-84](https://auth0team.atlassian.net/browse/CLI-84).
