### ISSUE TITLE
rename env.local.template to env.local after downloading qs

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#185]
Right now if after downloading the nextjs or node qs (auth0 quickstart download) and try to run it, it will fail. The reason is that env.local does not exist. There is env.local.template. If we could rename that to env.local after unzipping, the experience would be flawless

**Comment by Widcket** [comment]
No need to rename files anymore, as the Next.js sample is now using the `.example` extension, so the rename is handled by the Package Creator: https://github.com/auth0-samples/auth0-nextjs-samples/pull/14#issuecomment-806563116
