### ISSUE TITLE
empty rule template should have the default signature

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#188]
should be

```
function (user, context, callback) {
  // TODO: implement your rule
  return callback(null, user, context);
}
```

**Comment by Widcket** [comment]
This got fixed by https://github.com/auth0/auth0-cli/pull/186.

https://user-images.githubusercontent.com/5055789/112377831-f3ff3700-8cc4-11eb-96e3-d7cfb9c52193.mov
