### ISSUE TITLE
Cancel rule creation/update [CLI-86]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#189]
Add this hint when Editor opens:

```
Hint: once you close the editor, the rule will be saved. To cancel, CTRL+C.
```

**Comment by Widcket** [comment]
Tracking on [[CLI-86]](https://auth0team.atlassian.net/browse/CLI-86).

**Comment by cyx** [comment]
FYI I'm playing with the survey / prompt editor from the github client. If we ended up using that, we might have more steps, but also obviates the need for this.

Here's a sample @woloski: 

[![asciicast](https://asciinema.org/a/SRlL4zYsUJoJX6w7jzZoaIpWO.svg)](https://asciinema.org/a/SRlL4zYsUJoJX6w7jzZoaIpWO)
