### ISSUE TITLE
Keep "last client id created" in memory and offer that as the default for commands that require client ID [CLI-91]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#190]
![image](https://user-images.githubusercontent.com/175880/112389159-0b452100-8cd3-11eb-826e-4f34b86d8a90.png)

Instead of having to find the client id, we can offer the last client created as the default option (just store it in a global var in memory). Anywhere where we ask for client ID we should default to that. Delighter.

**Comment by Widcket** [comment]
We can store it in the config file so it survives across command invocations.

**Comment by Widcket** [comment]
Also, we can use it to select a default value in the picker (otherwise just the Client Id, devoid of all context, may be confusing to the dev that may no realize it is the Id of the app recently created).

**Comment by woloski** [comment]
yes. When I say default I meant that exactly (otherwise it would be too
much magic)

**Comment by Widcket** [comment]
This might have to be accompanied by an `auth0 apps use <client-id>` otherwise there's no way to change/unset it.

**Comment by Widcket** [comment]
Tracking in [CLI-91](https://auth0team.atlassian.net/browse/CLI-91).
