### ISSUE TITLE
After download the qs show me the README [CLI-85]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#191]
![image](https://user-images.githubusercontent.com/175880/112389371-66771380-8cd3-11eb-90db-b7d579219703.png)

After downloading QS for now we should tell the user to:

```
cd angular/sample-01
cat README.md
```

Better yet, do that programmatically and print the markdown using an MD pretty printer for console

**Comment by Widcket** [comment]
Tracking in [CLI-85](https://auth0team.atlassian.net/browse/CLI-85). Included in it `Use os.Chdir to cd into the downloaded sample dir`.

**Comment by cyx** [comment]
Done in #202
