### ISSUE TITLE
login error: You are polling faster than the specified interval of 5 seconds

### ISSUE THREAD

**Issue by brunokrebs** [auth0/auth0-cli#252]
On a MacOS X environment, I installed the CLI with brew and, right after logging in, I got the following error:

```bash
 ▸    ✪ Welcome to the Auth0 CLI 🎊.
 ▸    To set it up, you will need to sign in to your Auth0 account and authorize the CLI to access the API.
 ▸    If you don't have an account, please go to https://auth0.com/signup, otherwise continue in the browser.


 ▸    Your pairing code is: MJKV-RJLB

 ▸    This pairing code verifies your authentication with Auth0.
 ▸    Press Enter to open the browser (^C to quit)


===  error

 ▸    login error: You are polling faster than the specified interval of 5 seconds.
```

Just to confirm that the login flow indeed has failed, I ran `auth0 apps list`. As expected, I got:

```
===  error

 ▸    Not logged in. Try 'auth0 login'.
```

Running the flow again (`auth0 login`) succeeded. So, feel free to close the issue if you can't reproduce, but I leave it here as a note in case you want to double check.

**Comment by ssudaraka** [comment]
I've experienced the same issue. Tried again, but failed to login.
