### ISSUE TITLE
brew install is not working

### ISSUE THREAD

**Issue by guillermodoghel** [auth0/auth0-cli#255]
### Description

> Provide a clear and concise description of the issue, including what you expected to happen.
I cannot install the cli with brew
### Reproduction

`brew install auth0/auth0-cli/auth0`

```
==> Tapping auth0/auth0-cli
Cloning into '/opt/homebrew/Library/Taps/auth0/homebrew-auth0-cli'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 66 (delta 33), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (66/66), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/auth0/homebrew-auth0-cli/auth0.rb
formulae require at least a URL
Error: Cannot tap auth0/auth0-cli: invalid syntax in tap!
```

- **Version of this library used:**
- Homebrew 3.1.2
Homebrew/homebrew-core (git revision 2c472c983b; last commit 2021-04-19)
Homebrew/homebrew-cask (git revision b5fd8691ae; last commit 2021-04-20)

OS bigSur 11.2.3

**Comment by cpenarrieta** [comment]
Hello, I'm having the same issue.
Also `brew tap auth0/auth0-cli`  returns the same error.
My mac is an M1 Macbook Pro not sure if this is related to the error.

**Comment by Widcket** [comment]
@cpenarrieta thanks for sharing that. We're only building for x86 macs at the moment. I'll leave this issue open to track M1 support.

**Comment by Widcket** [comment]
@cpenarrieta [v0.6.0](https://github.com/auth0/auth0-cli/releases/tag/v0.6.0) is now out with support for M1 macs. Please ping if you run into any issues.

**Comment by cpenarrieta** [comment]
@Widcket just verified the fix and everything works! Thanks for the quick fix.
