### ISSUE TITLE
Add more user management capabilities in the CLI

### ISSUE THREAD

**Issue by haroldadmin** [auth0/auth0-cli#279]
### Describe the problem you'd like to have solved

Please add ability to search and delete users using the CLI. 

While developing an application, it is very useful to quickly search and delete users. I'd like to request the following functionality: 
- Search users by their email, Auth0 ID or their name
- Delete a user with the given Auth0 ID

### Describe the ideal solution

Search users:

`auth0 users search --email johndoe@example.com`
`auth0 users search auth0|123456`
`auth0 users search --name "John Doe"`

Delete users:

`auth0 users delete auth0|123456`

## Alternatives and current work-arounds

Use the Auth0 dashboard, which is much slower than using the CLI.

### Additional context

None.

**Comment by Widcket** [comment]
Hi @haroldadmin, thanks for requesting this feature. It certainly is in our roadmap, though there's no ETA.
I'll leave this issue open to track it.

**Comment by Widcket** [comment]
Implemented by #279.

**Comment by Widcket** [comment]
@haroldadmin this is now out on [v0.7.0](https://github.com/auth0/auth0-cli/releases/tag/v0.7.0).
