### ISSUE TITLE
Make it easier to copy a test token to the clipboard

### ISSUE THREAD

**Issue by novemberborn** [auth0/auth0-cli#315]
### Describe the problem you'd like to have solved

Having to select the access token is cumbersome. It should be easier to copy a test token to the clipboard.

### Describe the ideal solution

```console
auth0 test token | pbcopy
```

The CLI detects when stdout is not a TTY. When this is the case, it writes the access token to stdout. Any other messages are written to stderr. On macOS this should then allow me to automatically copy the access token to my clipboard, after which I can use it to make authenticated requests.

## Alternatives and current work-arounds

Select the access token and copy it manually.

**Comment by Widcket** [comment]
Hi @novemberborn, thanks for raising this. This is something we want to do, though we have no ETA. I'll leave this issue open to track it.

**Comment by Widcket** [comment]
@novemberborn this is now out in [v0.9.0](https://github.com/auth0/auth0-cli/releases/tag/v0.9.0).

**Comment by novemberborn** [comment]
@Widcket amazing!

**Comment by AndrewRayCode** [comment]
How is this feature supposed to work? None of these get the access token:

```
auth0 test login tenant --no-input --domain domain | echo
auth0 test login tenant --no-input --domain domain | xargs echo
auth0 test login tenant --no-input --domain domain | pbcopy
```
