### ISSUE TITLE
auth0 users create cant complete input

### ISSUE THREAD

**Issue by onlyhouse1980** [auth0/auth0-cli#334]
When trying to add a user via the auth0-cli I get the following error after I enter the password field.

macUser@iMac projectName % auth0 users create
json: cannot unmarshal string into Go struct field ConnectionList.connections of type []interface {}
 Connection: google-oauth2
 Name: Name
 Email: test@test.de
 Password: *********
json: cannot unmarshal string into Go struct field ConnectionList.connections of type []interface {}

!!     Uh oh. Something went wrong.
!!     If this problem keeps happening feel free to report an issue at
!!
!!     https://github.com/auth0/auth0-cli/issues/new/choose

This happens every time. 

using Next version 11.0.1
auth0 version 0.9.1 f9ab1c243c581e7aea0426f766ed10b289bbb52a
macOS Big Sur Terminal

**Comment by Widcket** [comment]
Hi @onlyhouse1980, users cannot be created via the CLI (or the dashboard) for social connections.

**Comment by Widcket** [comment]
We'll add this to the documentation of the `connection` flag of `users create`. Thanks for raising this.

**Comment by Widcket** [comment]
This is fixed in https://github.com/auth0/auth0-cli/releases/tag/v0.10.1.
