### ISSUE TITLE
Other option to authorize the client ?

### ISSUE THREAD

**Issue by dejwsz** [auth0/auth0-cli#337]
Is there any other option to authorize the client? For example using config file or env variables? Just to use it inside some CI/CD workflow to modify a list of origins, logout-url etc. In that case Device Authorization Flow is not an option.

**Comment by Widcket** [comment]
Hi @dejwsz, the CLI can be configured via env variables for CI usage. To do so, set up the following env vars:

`AUTH0_CLI_CLIENT_DOMAIN` -> your Auth0 tenant domain
`AUTH0_CLI_CLIENT_ID` -> your client id
`AUTH0_CLI_CLIENT_SECRET`-> your client secret

Then, run `auth0 config init`.

See https://github.com/auth0/auth0-cli/blob/main/Makefile#L61 and https://github.com/auth0/auth0-cli/blob/main/internal/cli/config.go

**Comment by dejwsz** [comment]
OK thx, will check it today.

**Comment by Widcket** [comment]
@dejwsz closing this one, please ping if you'd like to reopen.
