### ISSUE TITLE
--force and --no-input have no effect

### ISSUE THREAD

**Issue by AndrewRayCode** [auth0/auth0-cli#343]
### Description

--force and --no-input still prompt you to open a browser

### Reproduction

I'm trying to run a command to get a token to test with automatically:

```
auth0 test login MY_CLIENT_ID --no-input --force --domain MY_DOMAIN
```

This outputs:

> ▸    A browser window will open to begin this client's login flow.
> ▸    Once login is complete, you can return to the CLI to view user profile information and tokens.
>
> ▸    The client you are using does not currently allow callbacks to localhost.
> ▸    To complete the login flow the CLI needs to redirect logins to a local server and record the result.
>
> ▸    The client will be modified to update the allowed callback URLs, we'll remove them when done.
> ▸    If you do not wish to modify the client, you can abort now.
>
> Do you wish to proceed? (y/N)

According to the documentation from `auth0 help test login`:

```
      --force           Skip confirmation.
      --no-input        Disable interactivity.
```

This documentation isn't clear on what's supposed to happen, it is quite confusing. Either way, neither flag's supposed explanation is being followed, there is both a confirmation and it's interactive.

### Environment

> Please provide the following:

- **Version of this library used:**
auth0 --version
auth0 version 0.6.0 b69b35ae1f74e6b0caa1d96392fc575ffc0fafd8

- **Version of the platform or framework used, if applicable:**
Mac Big Sur, iTerm2

**Comment by Widcket** [comment]
Hi @AndrewRayCode, thanks for raising this. The `test login` command requires interactivity, because the login is browser-based. Therefore, the global flag `--no-input` has no effect. However, `--force` should work and open the browser tab directly without a confirmation prompt.
I'll leave this issue open to track that.

**Comment by Widcket** [comment]
> I'm trying to run a command to get a token to test with automatically
If you wish to obtain a test token, you can use the `auth0 test token` command.

E.g. `auth0 test token --audience "some-api"`

**Comment by Widcket** [comment]
The fix to have `test login` and `test token` honor the `--force` flaag is now out in [v0.11.0](https://github.com/auth0/auth0-cli/releases/tag/v0.11.0).
