### ISSUE TITLE
invalid_request: missing required paramter: response_type on "test login" command

### ISSUE THREAD

**Issue by sshurts** [auth0/auth0-cli#345]
downloaded the latest windows release.
performed:
    auth0 login  (was successful)
    auth0 test login (failed with error message in title).
    
    failure manifests in browser window before login.

**Comment by Widcket** [comment]
Hi @sshurts, thanks for reporting this.
What kind of app were you trying to log in to? (regular web app, spa, native?)
What flags did you pass, if any?

**Comment by sshurts** [comment]
Hi @Widcket, I have tried all three application types with the same result (web app, spa, machine 2 machine).
I did not try any flags.
I'm happy to try setting flags if you wish.

thanks
Scott

**Comment by sshurts** [comment]
[](url)

**Comment by sshurts** [comment]
I didn't mean to close this issue.  I thought I was deleting an empty comment

**Comment by sshurts** [comment]
Hi @Widcket,

What other information do you need in order to help resolve this issue?
I'm happy to try different flags, capture and post logs, etc.

thanks
Scott

**Comment by Widcket** [comment]
@sshurts can you try this with a proxy app like Proxyman? It would really help to see what params are being passed to the `authorize` endpoint.
