### ISSUE TITLE
Show app details by name

### ISSUE THREAD

**Issue by iegby** [auth0/auth0-cli#346]
My organization has many apps, more than fit on one page of the auth0 dashboard, and more than the 50 that are listed by `auth0 apps list`.   I often want to look up client id and secret by client name. I can think of two solutions that would work well for me:

1. Override the default maximum list size, for example:

```ps1
auth0 apps list --maxitems 500
auth0 apps show -r <client_id>
```

2. Show app details by name, for example:

```ps1
auth0 apps show -r --name <client_name>
```

Right now, I have to get this information from the Auth0 Dashboard by clicking through pages and using my browser's Find function.

**Comment by Widcket** [comment]
Hi @iegby, thanks for requesting this feature. This is something we need to address, so I'll leave this issue open to track it.

**Comment by Widcket** [comment]
It is out now in [v0.11.0](https://github.com/auth0/auth0-cli/releases/tag/v0.11.0).
