### ISSUE TITLE
Deploy actions once created

### ISSUE THREAD

**Issue by atsvetkov** [auth0/auth0-cli#352]
### Describe the problem you'd like to have solved

CLI allows to create an action and even specify a trigger, but it's not deployed (and there seems to be no command or flag to deploy via CLI at the moment). This means that customizing the actions still requires two manual actions on the Auth0 portal afterwards: deploying the action and then adding it to the flow.

### Describe the ideal solution

In order to fully support CLI-based provisioning of the tenants, it would be great to support deploying the action from CLI and/or adding it to the flow (not sure if the latter is feasible, given that other actions might already be there and that the order probably matters).

### Additional context

My main use case is provisioning the unified set of roles and permissions on multiple tenants corresponding to the deployment stages (dev, test, demo, production etc.). Our ideal goal would be to configure a tenant in a fully automated way: define API, permissions, standard roles, custom login actions - in essence, make tenant configuration reproducible, minimize manual work, and reduce human errors.

Are there any plans to support that or good reasons not to?

### Technical considerations

From looking at the Management API, I can see that [Deploy and action](https://auth0.com/docs/api/management/v2/#!/Actions/post_deploy_action) and [Update trigger bindings](https://auth0.com/docs/api/management/v2/#!/Actions/patch_bindings) methods would essentially allow to perform these steps, so it is at least theoretically possible.

**Comment by Widcket** [comment]
Hi @atsvetkov, the use case of configuring a tenant in an automated way for deployment is actually covered by the [deploy-cli](https://auth0.com/docs/deploy/deploy-cli-tool). This CLI is more geared towards human use (getting started, managing entities, etc).

**Comment by Widcket** [comment]
But we should probably cover more action endpoints, as the current support is pretty basic. I'll leave this issue open to track that.

**Comment by atsvetkov** [comment]
Thanks, that's a good point and I'll look into using the `auth0-deploy-cli` tool for our case. There's certainly a big overlap in what both tools allow to do, the only real difference being the intended use case. That's why it felt like the currently supported operations against Actions aren't complete yet (as in, creating an action via CLI isn't too helpful, if it can't be deployed and enabled right away).

@Widcket is there any guidance/roadmap regarding what those two CLI tools are going to grow into? To me they both seem like the Management API SDKs, with slightly different interfaces, but perhaps there is a more specific official position?

**Comment by Widcket** [comment]
I'm afraid there's no official position regarding that yet. But we're aware of the overlap.
