### ISSUE TITLE
CLI doesn't support more than 50 applications

### ISSUE THREAD

**Issue by sergeybykov** [auth0/auth0-cli#356]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If I run `auth0 apps list` in a tenant with more than 50 apps, I only get the first 50 (looks like in the order they were created) returned.

### Reproduction

Run `auth0 apps list` in a tenant with more than 50 apps.
Observe that only the first 50 apps are returned.

### Environment

auth0 version 0.10.3 0f57d1303347dd7bd7b8547ed81026b46b98089c
OSX zsh

**Comment by Widcket** [comment]
Hi @sergeybykov , thanks for raising this. Support for pagination was added in https://github.com/auth0/auth0-cli/pull/353, but it is yet unreleased. As soon as the other currently open PRs get reviewed and merged, we'll put a release out.

**Comment by sergeybykov** [comment]
Oh, excellent. Thank you, @Widcket!

**Comment by Widcket** [comment]
It is out now in [v0.11.0](https://github.com/auth0/auth0-cli/releases/tag/v0.11.0).

**Comment by sergeybykov** [comment]
@Widcket Confirmed that I can get all apps now.
Thank you!
