### ISSUE TITLE
Can't see the second tenant that's set up on my account

### ISSUE THREAD

**Issue by grreeenn** [auth0/auth0-cli#369]
### Description

I have 2 tenants available on my account - one of them is my own, opened when I first created an account, and second is the one managed by my organization and that I actually use to implement authorization in our apps.

The issue is that when I list tenants in CLI `auth0 tenants list`, I see only the first one, and don't see the one that I actually need. When I browse to the management page though, I can switch between the two with no problem.

Can it be a permissions issue? What permissions should I have to use CLI on a tenant managed by my company? I wanted to use the `auth0 branding templates update` feature.

### Reproduction

I'm not really sure why does it happen, so I'm not sure how to reproduce it exactly :(

### Environment

- **Version of this library used:** 0.11.2
- **Version of the platform or framework used, if applicable:** MacOS
- **Other relevant versions (language, server software, OS, browser):** Big Sur 11.6

**Comment by Widcket** [comment]
Hi @grreeenn, to have the tenant show up when you run `auth0 tenants list` you need to log into that tenant with `auth0 login`.

**Comment by grreeenn** [comment]
Hi @Widcket, 
Only after your comment I saw that select box on the permissions confirmation screen after logging in. Thanks a lot, closing :)
