### ISSUE TITLE
auth0-cli doesn't adhere to the BROWSER environment variable

### ISSUE THREAD

**Issue by trondhindenes** [auth0/auth0-cli#370]
when running `BROWSER=chromium auth0 login`, the signin prompt should open in the specified browser on supported OSes (mac+linux)

**Comment by Widcket** [comment]
Hi @trondhindenes, thanks for raising this. For the use case of opening the login URL in a non-default browser, we'd prefer to go with the solution of adding an option to print the login URL instead of opening a browser.
