### ISSUE TITLE
[Issue] Not able to Install auth0 cli use manual method in macOS Big Sur

### ISSUE THREAD

**Issue by adamchenwei** [auth0/auth0-cli#375]
### Description

When I attempted manual setup steps to install auth0 via downloaded `auth0-cli_0.11.3_Darwin_x86_64.tar.gz`
I get following error
`Last login: Thu Dec 16 13:56:13 on ttys014
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? /Users/user1/www/auth0 ; exit;
compinit: initialization aborted
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? Users/user1/www/auth0 ; exit;
compinit: initialization aborted
complete:13: command not found: compdef
user1@MACBOOK1 ~ % sers/user1/www/auth0 ; exit;
zsh: no such file or directory: sers/user1/www/auth0
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

I tried in case when I have nvm 0.35 and 0.38 seems there could be related issue, but the problem did not resolve.

### Environment
My macOS spec
<img width="582" alt="Screen Shot 2021-12-16 at 2 03 55 PM" src="https://user-images.githubusercontent.com/4201698/146432760-2d932bf0-505b-40b2-a7b4-f915ade48f19.png">
NOTE: I have to use BIgSur because I am not able to update to next OS version at this time.
> Please provide the following:

- **Version of this library used: `auth0-cli_0.11.3_Darwin_x86_64.tar.gz`

**Comment by Widcket** [comment]
Hi @adamchenwei, thanks for raising this.
nvm should not be an issue because this CLI is written in Go, and distributed as a single binary.
What is the specific installation step that is failing?

**Comment by adamchenwei** [comment]
@Widcket 

1. downloaded the build from https://github.com/auth0/auth0-cli/releases/tag/v0.11.3
2. unzipped into a folder in my mac
3. execute the unzipped file `auth0` via command line with `auth0 completion zsh > "${fpath[1]}/_auth0"`
4. Error encountered above.
Let me know if you need more detail.

**Comment by adamchenwei** [comment]
I solved it by having to upgrade my xcode to 13.x and then perform the brew install.
Manual install did not work for me. @Widcket I provided detail 4 days ago though, the tag "waiting for customer" is not exactly accurate haha

**Comment by Widcket** [comment]
@adamchenwei thanks for providing more information. That sounds like an issue with your shell environment, as Xcode is completely unrelated to the Auth0 CLI.
