### ISSUE TITLE
Add listing of roles assigned to members of an organization

### ISSUE THREAD

**Issue by sergeybykov** [auth0/auth0-cli#379]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently, there is no way to list what roles are used within an organization (assigned to its members). One can list all roles in a tenant, but this isn't very helpful because assignment of roles to organization members is a separate process.

### Describe the ideal solution

Add `roles` subcommand to the `orgs` command to list all roles used within the given organization, similar to the approach proposed in #377 for listing organization members.

## Alternatives and current work-arounds

The only alternative I'm aware of involves first listing members of the organization, and them querying roles assigned to each member, and merging the role lists. 

### Additional context

I'm happy to submit a PR with implementation if you are interested in adding this functionality. It would be a follow-up to #378.

**Comment by sergeybykov** [comment]
@Widcket This is a different feature - list roles and role members within an organization. I was just about to submit a PR for it.

**Comment by Widcket** [comment]
Oops, my bad 🙈. Reopened.

**Comment by sergiughf** [comment]
Closing this issue down as this is now available with https://github.com/auth0/auth0-cli/releases/tag/v0.11.6. Thanks a lot @sergeybykov for the contribution!
