### ISSUE TITLE
auth0 login opens finder instead of browser

### ISSUE THREAD

**Issue by th-m** [auth0/auth0-cli#408]
### Description
`auth0 login` command fails to open browser and instead opens finder winder. Then the command fails...
```
auth0 login --tenant marketplace-jobnimbus
✪ Welcome to the Auth0 CLI 🎊

If you don't have an account, please go to https://auth0.com/signup

Your Device Confirmation code is:

 ▸    Press Enter to open the browser to log in or ^C to quit...

Waiting for login to complete in browser... failed
```

### How to recreate
- install with homebrew `brew tap auth0/auth0-cli && brew install auth0`
- run the `auth0 login` command from iTerm or terminal on a mac. 

### Environment
macOS Monterey
MacBook Pro (14-inch, 2021)
Chip Apple M1 Pro
Using a .zsh profile w/ Iterm

- **Version of this library used:**
auth0 version 0.11.7 f9bcaf1b0d5c6c380022842b9707dfb8620b4890

**Comment by Widcket** [comment]
Hi @th-m, thanks for raising this.
This is known issue, see https://github.com/auth0/auth0-cli/issues/354.
You probably have set `AUTH0_CLIENT_ID`. As a workaround, you can pass `--no-input` to the login command, and it will print the login URL instead of trying to open it in the browser. Then you can copy and paste the URL in the browser and continue the login normally.

**Comment by Widcket** [comment]
See also https://github.com/auth0/auth0-cli/issues/392#issuecomment-1028537307 for another workaround.

**Comment by th-m** [comment]
Ah yes, I did have `AUTH0_CLIENT_ID` set. 

However even when passing in the `--no-input` I still was unable to get past the login flow. The command fails before I am able to do anything. Additionally there is no URL displayed to open just this message

```
~ auth0 login --no-input
✪ Welcome to the Auth0 CLI 🎊

If you don't have an account, please go to https://auth0.com/signup

Your Device Confirmation code is:

 ▸    Open the following URL in a browser:

Waiting for login to complete in browser... failed

===  error

 ▸    login error: Unauthorized
 ```

**Comment by th-m** [comment]
NVM I am a goof. I just had to remove the env var.

Thanks that worked
