### ISSUE TITLE
`auth0 branding templates update` fails to open external editor and cancels

### ISSUE THREAD

**Issue by jakeowenp** [auth0/auth0-cli#412]
### Description

When running `auth0 branding templates update` on an m1 mac with an external editor (e.g. vscode) - story book spins up, then instantly closes, and the html file opens as empty.

Tried with multiple m1 macs and Intel i5 macbook pro and multiple text editors - vscode/webstorm/atom.

Have always tried changing permissions and access in mac but not working

### Reproduction

1) set default editor in terminal to editor that requires new window, e.g. vscode
2) run `auth0 branding templates update`

### Environment

Macbook Pro
M1
MacOs 12.0.0
16gb Ram

**Comment by reujwils** [comment]
@jakeowenp @nickdaugherty I'm also stuck at the point this is describing and was curious if a solution was found?

**Comment by eugenf** [comment]
@nickdaugherty @reujwils I had the same issue and was able to fix it by setting the EDITOR var like this

`export EDITOR="code -w"`

**Comment by reujwils** [comment]
@eugenf Thanks, that worked for me 👍
