### ISSUE TITLE
Edit Forgot Password screen using `auth0 branding templates update`

### ISSUE THREAD

**Issue by jakeowenp** [auth0/auth0-cli#413]
### Describe the problem you'd like to have solved

On running `auth0 branding templates update` - can't update forgot password screen

<img width="398" alt="Screen Shot 2022-03-28 at 3 26 30 pm" src="https://user-images.githubusercontent.com/95193891/160326505-0e812305-c6b6-4267-9b83-accce1b383f4.png">

### Describe the ideal solution

Can edit forgot password screen using cli

## Alternatives and current work-arounds

Edit html text manually to look and triggers for forgot password

**Comment by sergiughf** [comment]
Hey @jakeowenp thanks for reporting this. We'll take a look soon into it.

**Comment by sergiught** [comment]
Hey @jakeowenp 👋🏻 more prompt screens were added in the latest release: https://github.com/auth0/auth0-cli/releases/tag/v0.12.0. Give it a go and let us know if you encounter any issues! Thanks for being patient with this one:)
