### ISSUE TITLE
Additional prompt screen states in branding template editing

### ISSUE THREAD

**Issue by AlanLeonard** [auth0/auth0-cli#415]
### Describe the problem you'd like to have solved

When running the `auth0 branding template update` command, I'm unable to view/address any visual issues within the prompt screen work flow beyond the initial views for Login, MFA and Signup. 

### Describe the ideal solution

Stories that document the different screen states would be ideal. For example: Login, Login with errors, MFA SMS Enrollment, MFA Authenticator Enrollment, MFA SMS verification. 

## Alternatives and current work-arounds

If I want to see how changes look deeper in the process, I need to make changes to the template, save, and then view on a safe environment, before moving up to Prod.

**Comment by sergiught** [comment]
Hey @AlanLeonard 👋🏻 more prompt screens were added in the latest release: https://github.com/auth0/auth0-cli/releases/tag/v0.12.0. Give it a go and let us know if you encounter any issues! Thanks for being patient with this one:)

**Comment by AlanLeonard** [comment]
Great news! Hope others will enjoy as well!
