### ISSUE TITLE
"auth0 logs tail" exits when certain server errors are encountered.  It should retry instead.

### ISSUE THREAD

**Issue by joshw** [auth0/auth0-cli#420]
### Description

If I (intentionally) leave `auth0 logs tail` running, it inevitably exits after encountering a server error at some point.

It should recover from such errors by retrying its query.  Exponential back-off is fine, if needed.

### Reproduction

```
% auth0 logs tail

....
                           Successful Refresh Token exchange                         3 seconds ago        N/A                     AdHoc
 ▸    An unexpected error occurred while getting logs: 502 Bad Gateway: Logs Service server responded with an internal error (potentially load-shedding)
```
### Environment

> Please provide the following:

- **Version of this library used:**
```
auth0 version 0.11.7 f9bcaf1b0d5c6c380022842b9707dfb8620b4890
```

- **Version of the platform or framework used, if applicable:**
n/a

- **Other relevant versions (language, server software, OS, browser):**
```
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64 x86_64
```

- **Other modules/plugins/libraries that might be involved:**
n/a

**Comment by willvedd** [comment]
More intentional retry logic for Management API requests was added in [v1.1.0](https://github.com/auth0/auth0-cli/releases/tag/v1.1.0). Notably for this issue, a fixed number of retries will occur for 502s, so I'm considering this issue satisfied.
