### ISSUE TITLE
Unable to login on Ubuntu-based systems

### ISSUE THREAD

**Issue by cs-jackb** [auth0/auth0-cli#446]
### Description

The Auth0 CLI cannot authenticate via the `auth0 login` command on Ubuntu based systems

#### Expected Results

-  For the `auth0 login` command to launch a browser window, wait for the login process to complete, and accept the response before continuing or exiting. 
-  For the `auth0 login --no-input` command to provide a URL, wait for the manual login process to complete, and accept the response before continuing or exiting. 

### Reproduction Steps

The `auth0 login` command, after prompting to continue or cancel, does not open the browser, produces an xdg-open error and exits with "login error: Unauthorized"

```bash
❯ date
Tue Jun  7 12:33:41 PM PDT 2022
❯ auth0 login
✪ Welcome to the Auth0 CLI 🎊

If you don't have an account, please go to https://auth0.com/signup

Your Device Confirmation code is: 

 ▸    Press Enter to open the browser to log in or ^C to quit...

xdg-open - opens a file or URL in the user's preferred application

Synopsis

xdg-open { file | URL }

xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.
 ▸    Couldn't open the URL, please do it manually: .
Waiting for login to complete in browser... failed

===  error

 ▸    login error: Unauthorized
❯ date
Tue Jun  7 12:33:50 PM PDT 2022
```

The `auth0 login --no-input` command does not provide a URL to open and immediately exits with "login error: Unauthorized".

```bash
❯ date
Tue Jun  7 12:34:45 PM PDT 2022
❯ auth0 login --no-input
✪ Welcome to the Auth0 CLI 🎊

If you don't have an account, please go to https://auth0.com/signup

Your Device Confirmation code is: 

 ▸    Open the following URL in a browser: 

Waiting for login to complete in browser... failed

===  error

 ▸    login error: Unauthorized
❯ date
Tue Jun  7 12:34:55 PM PDT 2022
```

In both cases, the "Device Confirmation code" is either not generated or not displayed. 

### Environment
```bash
❯ uname -a
Linux thinkpad-p52 5.17.5-76051705-generic #202204271406~1651504840~21.10~63e51bd SMP PREEMPT Mon May 2 15: x86_64 x86_64 x86_64 GNU/Linux
❯ /usr/bin/lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish
❯ auth0 --version
auth0 version 0.11.7 f9bcaf1b0d5c6c380022842b9707dfb8620b4890
❯ brew --version
Homebrew 3.5.0
Homebrew/homebrew-core (git revision 82433a6c1db; last commit 2022-06-06)
❯ xdg-open --version
xdg-open 1.1.3
```

**Comment by sergiughf** [comment]
Hey @cs-jackb thanks for opening this issue. 

Now I don't have an ubuntu installation handy but I did test this out on an arch linux and also docker ubuntu image as follows:

```bash
$ docker pull ubuntu
$ docker run -it ubuntu bash
$ apt update
$ apt install wget
$ wget https://github.com/auth0/auth0-cli/releases/download/v0.11.8/auth0-cli_0.11.8_Linux_arm64.tar.gz
$ tar -xvf auth0-cli_0.11.8_Linux_arm64.tar.gz
$ ./auth0 login
```

The output I got was the following:

```bash
root@872d59ccfbe4:/# ./auth0 login
✪ Welcome to the Auth0 CLI 🎊

If you don't have an account, please go to https://auth0.com/signup

Your Device Confirmation code is: REDACTED

 ▸    Press Enter to open the browser to log in or ^C to quit...

 ▸    Couldn't open the URL, please do it manually: https://auth0.auth0.com/activate?user_code=REDACTED.
Waiting for login to complete in browser... done

 ▸    Successfully logged in.
 ▸    Tenant: REDACTED.eu.auth0.com

 ▸    Could not store the refresh token locally, please expect to login again once your access token expired. See https://github.com/auth0/auth0-cli/blob/main/KNOWN-ISSUES.md.
```

Could you please confirm you don't have any AUTH0 env vars on your machine present? As those might affect the cli. e.g. `env | grep AUTH0`.

**Comment by cs-jackb** [comment]
> Could you please confirm you don't have any AUTH0 env vars on your machine present? As those might affect the cli. e.g. `env | grep AUTH0`.

That never even occurred to me; you were right - unsetting the `AUTH0_CLIENT_ID` and `AUTH0_CLIENT_SECRET` env variables (which were in place for the `a0deploy` CLI) allowed for successful login via the `auth0 login` command. It's not clear in the project source code how these variables would interfere. 

May I suggest adding a check to at least display a warning to the user when the AUTH0_CLIENT_ID is set to the client ID of an application that *is not* configured with the Device Code grant type? Or perhaps just updating the README.md with a short Troubleshooting section with a note about this, for now?

Regardless, thanks for the prompt solution!
