### ISSUE TITLE
Change default editor on windows

### ISSUE THREAD

**Issue by huneau** [auth0/auth0-cli#454]
I found something that could be changed for windows env

here => https://github.com/auth0/auth0-cli/blob/b303da9b6afe3b27c080a627532cb4348a6ec6b5/internal/prompt/editor.go#L134-L146

can you change the windows check at the end?

**Comment by jsoref** [comment]
Do note that at the very least until this is fixed, the documentation here:

https://github.com/auth0/auth0-cli#customization

is wrong.
