### ISSUE TITLE
auth0 actions update - Failure

### ISSUE THREAD

**Issue by marcelosantoro** [auth0/auth0-cli#462]
I am trying to run the command:

```
auth0 actions update <ID> --name "Match Email to Application" --trigger "post-login" --code "$VARIABLE_WITH_CODE"
```
But I am receiving this error:

```
400 Bad Request: can't upgrade to this trigger.
```

Is this a Bug... or i am missing something ?

**Comment by sergiught** [comment]
Hey @marcelosantoro 👋🏻 , apologies for the late reply on this one. 

The error you're getting comes directly from the Management API and it is not an issue with the cli. You're trying to update an action bound to a trigger from one type of a trigger to an incompatible one.

For example, let's say you have an action bound to a "post-login" trigger and you're trying to update it to a "pre-user-registration" trigger. That unfortunately won't work and will raise the error you're getting. 

Hope this helps! I'll close this down but feel free to reopen if needed.
