### ISSUE TITLE
Create Actions Help dialog typo 

### ISSUE THREAD

**Issue by tedsmitt** [auth0/auth0-cli#465]
https://github.com/auth0/auth0-cli/blob/7b0d17c56b5aeb670336077d6aa22203e39082cd/internal/cli/actions.go#L173-L175

Extra dash here in front of `-n` only noticed this because I tried copy+pasting the command 😅 

```
=== dev-edintheclouds.eu.auth0.com error

 ▸    unknown flag: --n
```

**Comment by sergiught** [comment]
Hey @tedsmitt thanks for reporting this and kudos to @jsoref for fixing this through #477 !
