### ISSUE TITLE
Permission Denied Error: Failed to capture input from the editor

### ISSUE THREAD

**Issue by joncursi** [auth0/auth0-cli#472]
### Description

I have installed the Auth0 CLI via Homebrew on macOS. When I run `auth0 branding templates update`, I get the following permissions error:

```
 ▸    Failed to capture input from the editor: An unexpected error occurred: exec: "/usr/local/share/nvim": permission denied
 ▸    Unexpected error while previewing custom template: %!w(*fs.PathError=&{lstat /var/folders/my/lb1w0ddn50q4ms73h0w1393r0000gn/T/custom-template.2876940648.html 2})
```

Ideas on how to get through this permission error with `nvim`?

### Environment

> Please provide the following:

- **Version of this library used:** `auth0 version 0.11.10 285359e60f4606978799b0803ed8c0fb9dd6071b`
- **Other relevant versions (language, server software, OS, browser):** macOS Monterey 12.5

**Comment by sergiught** [comment]
Hey @joncursi, 

You're probably (pure guessing without further info) running the auth0-cli as a non root user and you installed NeoVim as root. Make sure the user that runs auth0-cli can run NeoVim (nvim) to fix the issue. Alternatively you could use a different EDITOR following: https://github.com/auth0/auth0-cli#customization or running the following command `EDITOR=nano auth0 branding templates update`. Let me know if this helps! 🙏🏻

**Comment by sergiught** [comment]
Closing this down as we haven't heard back from you and it's very likely an env configuration issue on your machine. Feel free to reopen if needed tho!
