### ISSUE TITLE
No headers in `auth0 logs`

### ISSUE THREAD

**Issue by bgolding355** [auth0/auth0-cli#474]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When you run `auth0 logs -n 3` you see something like this (without the header)
???|???|???|???
-|-|-|-
Success Silent Auth    |7 minutes ago|N/A                 |APP1 
Success Cross Origin...|9 minutes ago|Username-Password...|APP2 
Success Logout         |9 minutes ago|N/A                 |N/A

### Describe the ideal solution

It can sometimes be unclear what each cell refers to. Adding headers would help

## Alternatives and current work-arounds

Use `manage.auth0.com` to view logs

### Additional context

Currently using auth0 version: `auth0 version 0.11.10 285359e60f4606978799b0803ed8c0fb9dd6071b`

**Comment by willvedd** [comment]
**Update:** We've included fix for this in the [v1.0.0-beta.1](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0-beta.1) release. For those who are so inclined, we'd be happy to receive feedback on the beta before it goes GA, including feedback on this particular issue. Otherwise, we plan to close this issue out once v1.0.0 reaches GA. Again, appreciate everyone's patience!

**Comment by willvedd** [comment]
We've fixed this by adding headers for `auth0 logs list` and `auth0 logs tail` commands in the [v1.0.0](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0) release. We encourage folks to upgrade and give it a shot!
