### ISSUE TITLE
Provide way to make arbitrary api calls

### ISSUE THREAD

**Issue by jsoref** [auth0/auth0-cli#479]
### Describe the problem you'd like to have solved

I have a broken app (caused entirely by the Auth0 apis, either directly by manage.auth0.com, or possibly by terraform-auth0, or possibly by auth0-cli).

https://github.com/auth0/terraform-provider-auth0/issues/266#issuecomment-1211763324 suggested that I could use  https://auth0.com/docs/api/management/v2#!/Clients/patch_clients_by_id to fix my app.

I'd like to be able to perform that api call using the `auth0` cli.

### Describe the ideal solution

The auth0 cli appears to be modeled after [`gh`](https://github.com/cli/cli) which provides [`gh api`](https://cli.github.com/manual/gh_api) which enables one to make authenticated api calls.

I'd like to be able to use `auth0 api` in the same manner (and be told by the documentation that currently suggests the web page w/ a form that doesn't work how to perform the api calls using that feature...)

## Alternatives and current work-arounds

I could probably create a new token and manually use curl, but since I have already set up `auth0` and it's supposed to be a shiny frontend to the auth0 management api, it should really just do what I need.

### Additional context

https://github.com/cli/cli/blob/6a8deb1f5a9f2aa0ace2eb154523f3b9f23a05ae/pkg/cmd/api/api.go#L65-L68
https://github.com/cli/cli/blob/6a8deb1f5a9f2aa0ace2eb154523f3b9f23a05ae/pkg/cmd/api/api.go#L83-L96

**Comment by sergiught** [comment]
Hey @jsoref 👋🏻 , thanks for the feature request!

This was added in the latest release https://github.com/auth0/auth0-cli/releases/tag/v0.13.0 and it is now available when using the device code flow authentication. 

Please give it a try and let us know if you encounter any issues.

**Comment by jsoref** [comment]
Awesome. I imagine we'll be revisiting poking auth0 w/in the next 3 months, so I expect we'll look then.

(We recently started working on retooling the chain that led to this request.)
