### ISSUE TITLE
Script Tags break storybook branding update

### ISSUE THREAD

**Issue by lucasmpr** [auth0/auth0-cli#482]
### Description

I'm trying to customize the login page using a little bit of javascript, but storybook breaks whenever there is a javascript code. 
The development flow is a bit broken by having to upload every change.

### Reproduction

1. Run ```    auth0 branding templates update  ```
2. Input a script tag with anything: ```<script> console.log("A")</script>```
3. Go see the result in storybook.

This is the result here: 

![image](https://user-images.githubusercontent.com/1821059/187467968-037d0ede-e5c2-4690-be31-67321606a340.png)

"`); iframe.contentWindow.document.close();"

### Environment

> Please provide the following:

- **Version of this library used:** 0.11.9
- **Other relevant versions (language, server software, OS, browser):**  Windows 11 - Chrome

**Comment by mtj8033** [comment]
having the same issue, was anyone able to work around this?

**Comment by sergiught** [comment]
Hey folks thanks for reporting and apologies for the delay! We've added a small comment with v1 in https://github.com/auth0/auth0-cli/blob/e53b3d32943d0346c25e075d2607fec0fe3ebcbb/internal/cli/data/branding/image-template.liquid#L34 when you open the template with a script example in it, so this should be resolved now. If you feel it's still not enough please let us know and we can reopen this.
