### ISSUE TITLE
pagination in user search

### ISSUE THREAD

**Issue by mdave16** [auth0/auth0-cli#485]
**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I want to get a list of all users who fit a certain criteria. Using the api I could use pagination to return many users. Using the cli, it returns a max of 50 users. This is fine, but how can I get the older users. 

### Describe the ideal solution

`auth0 users search -q 'user_metadata.city: "Seattle"' -p 2 (--page 2) -l 60 (--limit 60)` 
 and this returns a list of users similar to the api...

## Alternatives and current work-arounds

I can write a script that will analyse the last created and then add the filter that created by is before a certain date, join these data bits together, (or user export in the UI, or through management api similar to #475 ) 
This helps to get to the same end result as #475 but is a different functionality so I've chosen to create a new one, if you feel they are similar enough, feel free to close this one.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by willvedd** [comment]
**Update:** We've included fix for this in the [v1.0.0-beta.1](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0-beta.1) release. For those who are so inclined, we'd be happy to receive feedback on the beta before it goes GA, including feedback on this particular issue. Otherwise, we plan to close this issue out once v1.0.0 reaches GA. Again, appreciate everyone's patience!

**Comment by willvedd** [comment]
Fixed and released in our [v1.0.0](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0) release. We encourage folks to upgrade and give it a shot!
