### ISSUE TITLE
Add client secret to output when creating a regular web application

### ISSUE THREAD

**Issue by mraible** [auth0/auth0-cli#488]
### Describe the problem you'd like to have solved

Currently, when you create a **Regular Web Application** using `auth0 apps create`, it doesn't display the client secret in the output. You have to run `auth0 apps open` to get the client secret. This is kind of a pain for developers doing tutorials using the CLI.

### Describe the ideal solution

The client secret appears below the client ID. 

## Alternatives and current workarounds

```
auth0 apps open
```

**Comment by willvedd** [comment]
@mraible This is currently possible with the `--reveal` flag. However, I do admit that flag doesn't intuitively describe what it reveals. In the next major version of the CLI we intend to rename this flag to `--reveal-client-secret` to be more descriptive and self-documenting.

**Comment by mraible** [comment]
The `--reveal` flag doesn't seem to work with `auth0 apps show`. Should it?

```
$ auth0 apps show --reveal

=== dev-06bzs1cu.us.auth0.com error

 ▸    unknown flag: --reveal
$ auth0 apps show --reveal-client-secret

=== dev-06bzs1cu.us.auth0.com error

 ▸    unknown flag: --reveal-client-secret
```

**Comment by sergiught** [comment]
@mraible it's `--reveal-secrets`

You can run `auth0 apps show -h` to get a quick preview of the usages/examples/help text for the command and its flags.

```
Display the name, description, app type, and other information about an application.

Usage:
  auth0 apps show [flags]

Examples:
  auth0 apps show
  auth0 apps show <app-id>
  auth0 apps show <app-id> --reveal-secrets
  auth0 apps show <app-id> -r --json

Flags:
  -h, --help             Help for show.
      --json             Output in json format.
  -r, --reveal-secrets   Display the application secrets ('signing_keys', 'client_secret') as part of the command output.

Global Flags:
      --debug           Enable debug mode.
      --no-color        Disable colors.
      --no-input        Disable interactivity.
      --tenant string   Specific tenant to use.
```

**Comment by mraible** [comment]
This works. Thanks @sergiught!
