### ISSUE TITLE
auth0 test token ignoring --no-input

### ISSUE THREAD

**Issue by jakedotfive** [auth0/auth0-cli#511]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the `auth0 test token --no-input` it fails to display the URL instead trying to open a browser window.

checking the code also confirms this behaviour

### Expectation

When using the `auth0 test token --no-input` it should display a url, similar to how `auth0 login --no-input` works

### Reproduction

1. Install auth0-cli
2. `auth0 test token --force --no-input --audience <audience>`
3. Should display url to click and authenticate externally

### Auth0 CLI version

0.12.0

**Comment by willvedd** [comment]
**Update:** We've included fix for this in the [v1.0.0-beta.1](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0-beta.1) release. For those who are so inclined, we'd be happy to receive feedback on the beta before it goes GA, including feedback on this particular issue. Otherwise, we plan to close this issue out once v1.0.0 reaches GA. Again, appreciate everyone's patience!

**Comment by willvedd** [comment]
Fixed and released in our [v1.0.0](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0) release. We encourage folks to upgrade and give it a shot!
