### ISSUE TITLE
CLI completely freezes on WSL2

### ISSUE THREAD

**Issue by jarpoole** [auth0/auth0-cli#760]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The CLI is completely unresponsive after installation on WSL2. I tried multiple installation options including from source, for linux using cURL and from brew.

The only command I can run successfully is `auth0 --help` and ONLY if I have not attempted to run any other command before that. Once auth0 locks up I have to restart wsl with `wsl --shutdown` to recover. Hopefully you understand that for this reason I haven't gotten to play around with it a lot.

For greater clarity, this is exactly what happens when I run an auth0 command: 
![image](https://github.com/auth0/auth0-cli/assets/43940867/283e9711-dc2c-41d1-85a1-85ee98fe6979)

Given the CLI is past its 1.0.0 release I thought it might be stable but maybe WSL2 is not a supported environment? If so this should be explicitly mentioned given its popularity.

I'm using `Ubuntu-20.04`. Here is the result of `uname -a`

```
Linux JaredPC 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Expectation

That the CLI is responsive and works???

### Reproduction

1. Install the auth0 CLI following the Linux instructions: `curl -sSfL https://raw.githubusercontent.com/auth0/auth0-cli/main/install.sh | sh -s -- -b .`
2. Add to path
3. Run any auth0 cli command. For example `auth0 login`.

### Auth0 CLI version

1.0.1

**Comment by jimhess** [comment]
Upvote - same issues.  
It may run 1 time after install eg `./auth0 -v` to get the version, but any subsequent will "hang".

**Comment by m3talsmith** [comment]
@jarpoole and @jimhess , I'm trying to reproduce this and wondered if the latest version (1.2.0) works for you. Here's how I installed the specific version on my WSL2 instance:

```shell
curl -sSfL https://raw.githubusercontent.com/auth0/auth0-cli/main/install.sh | sh -s -- -b . v1.2.0
sudo mv auth0 /usr/local/bin/
```

The version at the end of the curl represent the version that you are installing. By default it is the latest, so pinning the version might help us reproduce this together.

I did attempt reproducing with `v1.0.1` without result. My WSL2 version is `5.10.102.1-microsoft-standard-WSL2`, which is the store default as of today. Perhaps there's a difference in `5.10..5.15`?

Please let us know if the latest is still causing issues.

**Comment by jarpoole** [comment]
@m3talsmith thank you for following up! Trying installation commands you recommended above everything seems to be working perfectly now! I'll close this now because it seems like things got resolved with time...
