### ISSUE TITLE
Universal login:  Choice of editor 

### ISSUE THREAD

**Issue by indcoder** [auth0/auth0-cli#780]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Right now when you update the universal login template

<img width="473" alt="image" src="https://github.com/auth0/auth0-cli/assets/2099300/765a14b2-eba4-4ab6-bf0c-d5e638f4f1c2">

You get a storybook browser tab opening up, and notepad for the html code. But my workstation is configured to have .html file open up in VS Code. But the file with html code, instead of having an extension of .html, has a 9-digit numeric extension

<img width="755" alt="image" src="https://github.com/auth0/auth0-cli/assets/2099300/eb6c93ae-365c-4333-afc1-35773814ddae">

This implies I miss out on a rapid html authoring experience that I have already configured with my VS Code, and the notepad is prone to many typos etc

### Describe the ideal solution

Since my VS Code has been configured for an awesome html authoring experience, I would rather be it configurable as to which editor the cli should open for the html authoring file.

**Comment by Zertz** [comment]
For the environment variable to be persistent:

- Start menu
- Search: _variables_
- Click _Environment variables_
- Click _New..._
  - Name: `EDITOR`
  - Value: `code --wait`

Restart your terminal and every tool using this variable will not open with VS Code.
