### ISSUE TITLE
Terraform generate command not found.

### ISSUE THREAD

**Issue by sarah-hanley** [auth0/auth0-cli#814]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The command `auth0 terraform generate` as shown in the documentation returns `unknown command "terraform" for "auth0"`. [auth0 documentation](https://auth0.github.io/auth0-cli/auth0_terraform_generate.html )

### Expectation

I expect the command to run and generate terraform files

### Reproduction

1. install the auth0-cli per the docs with brew
2. run `auth0 login` and sign into tenant
3. run `auth0 terraform generate`

### Auth0 CLI version

auth0 version 1.0.1 15dd3c4559c46c8e3dd5a4d0d9b4a849fea0cb1a

**Comment by sergiught** [comment]
Hey @sarah-hanley 👋🏻 

Thanks for the interest in giving the terraform generate command a go! Sadly this feature hasn't been released yet as it's still under active development; agreed that having the docs already mention it is confusing, we'll work on fixing this. 

Once we cut a release and introduce the command we'll give you a heads up!

**Comment by willvedd** [comment]
@sarah-hanley Good news, the `auth0 tf generate` command has been released in [v1.1.0](https://github.com/auth0/auth0-cli/releases/tag/v1.1.0). Please update and give it a go!

We also have an [instructional guide](https://registry.terraform.io/providers/auth0/auth0/latest/docs/guides/generate_terraform_config) to go along with it. Hope that helps!
