### ISSUE TITLE
Can only provide 1 secret to actions

### ISSUE THREAD

**Issue by Tenrys** [auth0/auth0-cli#841]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

According to the docs for the `auth0 actions` category, you can supply secrets through multiple `-s` or `--secret` flags, but from what I found, only the last secret is taken into account.

![image](https://github.com/auth0/auth0-cli/assets/3979239/1bdb3132-2002-483f-ade2-869958d4b575)

![image](https://github.com/auth0/auth0-cli/assets/3979239/b8e209e3-6271-4a98-8c4e-bf9e82e5d3d7)

### Expectation

I should be able to supply multiple secrets to an action through the CLI.

### Reproduction

1. Run this command 
	`auth0 actions create -n test-post-login -t post-login -c "test" -s "TEST1=1" -s "TEST2=2"`
2. Have a look on the Auth0 dashboard, in your new Custom Action's secrets tab. You'll see that only `TEST2` can be seen.

### Auth0 CLI version

`auth0 version 1.0.1 15dd3c4559c46c8e3dd5a4d0d9b4a849fea0cb1a`

**Comment by Tenrys** [comment]
I made a PR that would fix this issue here: https://github.com/auth0/auth0-cli/pull/843

**Comment by willvedd** [comment]
@Tenrys Nice find! You're correct about the bug here, you should be able to pass multiple secrets to the CLI. As you've also discovered, this is due to the reassignment of a pointer inside the loop. Apologies about the duplicate PR, I had already begun looking into it. Rest assured that this will be included in an upcoming release very soon! Thanks for your help.

**Comment by willvedd** [comment]
This has been fixed in [v1.1.0](https://github.com/auth0/auth0-cli/releases/tag/v1.1.0). Thanks for reporting!
