### ISSUE TITLE
Sign with an Apple developer key

### ISSUE THREAD

**Issue by astanciu** [auth0/auth0-cli#92]
![image](https://user-images.githubusercontent.com/1675025/107075599-55705280-67b8-11eb-8783-a998e659483d.png)

**Comment by jfatta** [comment]
It seems like installing with homebrew is not requiring this.

````
brew install auth0/auth0-cli/auth0
````

**Comment by jfatta** [comment]
I think we can close this
@Widcket @astanciu ?

**Comment by Widcket** [comment]
Closing this issue for now.
