### ISSUE TITLE
Client credentials auth failing when no keyring

### ISSUE THREAD

**Issue by mgrand-kubra** [auth0/auth0-cli#933]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have run into a problem with the Auth0 CLI’s login command in WSL Ubuntu under Windows 10. Here is a log of what happens:

```
mgrand@TX-L5062-23:/mnt/c/Users/mgrand/IdeaProjects/auth0-terraform$ auth0 login --domain $AUTH0_DOMAIN --client-id $AUTH0_CLIENT_ID --client-secret $AUTH0_CLIENT_SECRET
? Could not store the client secret and the access token to the keyring: dial unix /run/user/1000/bus: connect: no such file or directory
? Expect to login again when your access token expires.
? Successfully logged in.
? Tenant: [terraform-sandbox.kubra-idp-dev.auth0.com](https://terraform-sandbox.kubra-idp-dev.auth0.com/)
? Hint: Switch between authenticated tenants with `auth0 tenants use <tenant>`
mgrand@TX-L5062-23:/mnt/c/Users/mgrand/IdeaProjects/auth0-terraform$ auth0 tf generate --output-dir tmp

=== error

? failed to fetch access token using client credentials: failed to retrieve client secret from keyring: dial unix /run/user/1000/bus: connect: no such file or directory
This may occur if the designated Auth0 application has been deleted, the client secret has been rotated or previous failure to store client secret in the keyring.
```

### Expectation

I expected the login to work and leave a credential that other commands can use.

### Reproduction

1. Install WSL2 in Windows 10 environment.
2. Install Ubuntu in WSL2.
3. Install the CLI
4. Try logging it.

### Auth0 CLI version

auth0 version 1.2.0 046bdd3b91436fc2cc37a80bef6357e2cdfcc106

**Comment by willvedd** [comment]
I believe that this was resolved with #919 and released with [1.3.0](https://github.com/auth0/auth0-cli/releases/tag/v1.3.0). Are you able to upgrade and retry?

**Comment by mgrand-kubra** [comment]
I upgraded and now I am seeing a different message:
>
> ***@***.***:~/tmp$ auth0 --version
> auth0 version 1.3.0 2bd069cfc1ee0501ed039fc80b2e550447c8ef14
> ***@***.***:~/tmp$ auth0 login --domain $AUTH0_DOMAIN --client-id
> $AUTH0_CLIENT_ID --client-secret $AUTH0_CLIENT_SECRET
>  ▸    Could not store the client secret and the access token to the
> keyring: The name org.freedesktop.secrets was not provided by any .service
> files
>  ▸    Expect to login again when your access token expires.
>
>  ▸    Successfully logged in.
>  ▸    Tenant: terraform-sandbox2.kubra-idp-dev.auth0.com
>  ▸    Hint: Switch between authenticated tenants with `auth0 tenants use
> <tenant>`
> ***@***.***:~/tmp$ auth0 tf generate --output-dir tmp
>
> === dev.kubra-idp-dev.auth0.com error
>
>  ▸    failed to fetch access token using client credentials: failed to
> retrieve client secret from keyring: The name org.freedesktop.secrets was
> not provided by any .service files
>
> This may occur if the designated Auth0 application has been deleted, the
> client secret has been rotated or previous failure to store client secret
> in the keyring.
>
> Please re-authenticate by running: auth0 login --domain <tenant-domain
> --client-id <client-id> --client-secret <client-secret>
> ***@***.***:~/tmp$
>

**Comment by m3talsmith** [comment]
@mgrand-kubra I'm looking into this and I want to make sure my setup is close to yours. What version of WSL2 does `uname -a` give you? Mine is `5.15.133.1-microsoft-standard-WSL2`

**Comment by mgrand-kubra** [comment]
We are on the same version. Here is the full information:

***@***.***:~$ uname -a
Linux TX-L5062-23 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5
21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by m3talsmith** [comment]
@mgrand-kubra I found one way to duplicate the second error, but it required me to remove the `access_token` key from a tenant in `~/.config/auth0/config.js`. When I logged back in, it healed itself. Is there any chance that the file got corrupted or hand-edited?

I did try multiple ways of failing, including removing the write permission from the config file. None of the other forms gave that error message.

Do you mind trying to remove `~/.config/auth0/config.json` and re-signing in? If that doesn't work, at least we've eliminated one known possibility.

**Comment by mgrand-kubra** [comment]
Removing  ~/.config/auth0/config.json solved my problem. Thank you.
