### ISSUE TITLE
auth0 organizations members list org_xxx error when outputting json

### ISSUE THREAD

**Issue by anthonyangel** [auth0/auth0-cli#948]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

`auth0 organizations members list org_xxx` outputs in table format by default, but according to the docs `auth0 organizations members list org_xxx --json` should output a json list of objects.

What the command with `--json` does is output a json list of objects of the correct length (ie it matches the number of users) but every user object is the last user in the list.

### Expectation

Expecting to see a list of objects corresponding to the users in an organization

### Reproduction

1.) Run `auth0 organizations members list org_xxx`, (with a valid org ID) - validate that you see a table output
2.) Run `auth0 organizations members list org_xxx --json`, (with a valid org ID) - validate that you see the json output with a single user repeated multiple times

### Auth0 CLI version

auth0 version 1.3.0 2bd069cfc1ee0501ed039fc80b2e550447c8ef14

**Comment by m3talsmith** [comment]
@anthonyangel thanks for the report. We found the bug and it's merged in main. We'll get it out in the next release.
