### ISSUE TITLE
Swift Package Index shows it failed tests for visionOS: https://swiftpackageindex.com/auth0/Auth0.swift

### ISSUE THREAD

**Issue by mikehihz** [auth0/auth0-cli#952]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Swift Package Index shows it failed tests for visionOS: https://swiftpackageindex.com/auth0/Auth0.swift

### Expectation

Hoping for a green check mark on visionOS

### Reproduction

Not tried. Apple engineering would like to have a dialog. Please contact Michael Wong at wong@apple.com

### Auth0 CLI version

2.5.0

**Comment by willvedd** [comment]
Wrong repo. Please re-open at https://github.com/auth0/Auth0.swift
