### ISSUE TITLE
Add capability to export logs as type csv not just json.

### ISSUE THREAD

**Issue by DannyPat44** [auth0/auth0-cli#954]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I was investigating some issues in our tenant and wanted to export some logs to a .csv file so we can count specific issues and share them with our customer success and support teams. Specifically, you can load the .csv to Excel, which is a friendly tool for non-developers. 

### Describe the ideal solution

I was able to do it, but I had to do some `jq` manipulation, which was a bit painful. It would be nice to have a similar flag as `--json` for csv or have the formatting to the log table be more straightforward to parse to .csv. 

### Alternatives and current workarounds

I was able to use this to build a csv file from the json output. But it took more effort than I would have liked. 
`auth0 logs list --filter "type: f AND date:[2023-12-25 TO 2024-01-02]" --json | jq -r '["type", "date", "description", "connection", "client_name", "user_agent"], (.[] | [.type, .date, .description, .connection, .client_name, .user_agent]) | @csv ' >> ~/Downloads/ben-logs.csv`

I tried using `tr` and `sed` but found that both would not properly break the file apart with the current output formating. 
`auth0 logs list --filter "type: f AND date:[2023-12-25 TO 2024-01-02]" | tr "\\t" "," >> ~/Downloads/amh-logs.csv`

### Additional context

I love the new CLI tool. Overall, it is a great addition to help developers troubleshoot.

**Comment by m3talsmith** [comment]
@DannyPat44 I'm working on a CSV export for another command and looking at generalizing the format. I'll keep logs in mind as I think it's a good fit too. Update you as it comes together.

**Comment by m3talsmith** [comment]
@DannyPat44 #955 brings the `--csv` flag to logs and all the rest of our table result-based commands. This should be merged today into the main branch and make it into the next release.

An example of using it in your case would be:

```
auth0 logs list --filter "type: f AND date:[2023-12-25 TO 2024-01-02]" --csv > ~/Downloads/ben-logs.csv
```

**Comment by DannyPat44** [comment]
Wow, that was so quick! Thank you.
