### ISSUE TITLE
auth0 terraform generate command does not create imports for auth0_client_credentials resources

### ISSUE THREAD

**Issue by hyei** [auth0/auth0-cli#980]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the auth0 terraform generate command on one of auth0 tenants, the auth0_client_credentials resource is not imported within auth0_import.tf 

### Expectation

I expect all auth0 resources to be generated from my tenant so as to be able to replicate my tenants settings in another tenant.

### Reproduction

Consistently reproduced:
1. Via the auth0 Dashboard, create and configure a tenant with at least one application/client with Applcation Type: regular_web, and change the default credentials from "Client Secret (Post)" to "None"
2. Setup the auth0 cli with the tenant and run cmd: auth0 terraform generate --tenant <tenant name>
3. auth0_import.tf is generated.

Terraform file does not include any import statements for the auth0_client_credentials resources. 

### Auth0 CLI version

1.4.0 54e9a30eeb58a4a7e40e04dc19af6869036bfb32

**Comment by duedares-rvj** [comment]
Closing this since changes has been released.
