### ISSUE TITLE
Unable to create a passwordless user 

### ISSUE THREAD

**Issue by ivinapontes** [auth0/auth0-cli#989]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://auth0.github.io/auth0-cli/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-cli/releases/latest) of this project and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Unable to create passwordless user via auth0-cli because it requires a password even when providing "email" as type of connection

### Expectation

I should be able to create a passwordless user without the need to provide a password 

### Reproduction

 I'm entering the following command: 
 >  auth0 users create --name "John Doe" --email john@example.com
and then choose the connection name 
 Connection Name: email
 
it then requests a password, but the journey is passwordless, any password I get this error back 
Failed to create user: 400 Bad Request: "password" is not allowed.

### Auth0 CLI version

1.4.0

**Comment by ramya18101** [comment]
Hi @ivinapontes 

Apologies for the late response,  We previously didn't support generating passwordless users with auth0-cli, Now we made changes to allow creating users with both email and SMS connections as part of the release [v1.6.0](https://github.com/auth0/auth0-cli/releases/tag/v1.6.0) and we are closing the issue.

Please feel free to re-open the issue if you have any concerns.
