### ISSUE TITLE
Custom Prompt Support with "auth0 universal-login customize" command

### ISSUE THREAD

**Issue by WorldOfByrd** [auth0/auth0-cli#997]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to preview and deploy Custom Prompts from the Auth0 CLI, similar to custom text and theme settings when running `auth0 universal-login customize` 

### Describe the ideal solution

A new tab in the WYSIWYG editor that allows you to create, update and view Custom Prompts rather than needing to deploy to an environment to review look and feel.

This would assist in live editing and troubleshooting, and speed up time-to-deliver for additional Custom Prompts.

**Comment by westlywright** [comment]
This is absolutely needed, you should not have to deploy to a live environment, regardless if the environment is production or develop etc., to test custom prompts.

**Comment by tylerkeesling** [comment]
You can checkout our latest update on this [here](https://auth0.com/changelog#VGNKvp0wOwJrdIuK0BpWd).

**Comment by developerkunal** [comment]
Hi @WorldOfByrd,

Apologies for the delayed response. This feature has already been released, so we will be closing this issue.

Thank you for your understanding!
